sonarr:
    ingress:
        main:
            enabled: true
            className: traefik
    persistence:
            media:
                enabled: true
                existingClaim: jellyfin-media
            config:
                enabled: false
                existingClaim: jellyfin-config
