sonarr:
    persistence:
        media:
            enabled: false
            exitingClaim: jellyfin-media
            accessMode: ReadWriteMany
        config:
            enabled: false
            existingClaim: jellyfin-config
            accessMode: ReadWriteOnce
    