sonarr:
    persistence:
        common:
            media:
                enabled: true
                existingClaim: jellyfin-media
            config:
                enabled: false
                existingClaim: jellyfin-config
