sonarr:
    persistence:
        media:
            enabled: true
            exitingClaim: jellyfin-media
            accessMode: ReadWriteMany
        config:
            enabled: true
            existingClaim: jellyfin-config
            accessMode: ReadWriteOnce
    