common:
    persistence:
        media:
            enabled: true
            existingClaim: jellyfin-media
sonarr:
        config:
            enabled: false
            existingClaim: jellyfin-config
            accessMode: ReadWriteOnce
    