sabnzbd:
  livenessProbe:
    httpGet:
      path: /
      port: http
  readinessProbe:
    httpGet:
      path: /
      port: http

  service:
    type: ClusterIP
    port: 8080

  env:
    - name: PUID
      value: "65533"
    - name: PGID
      value: "65533"
    - name: TZ
      value: "Europe/London"

  ingress:
    enabled: true
    className: traefik
    hosts:
      - host: sabnzbd.k3s.micasa.systems
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - hosts:
        - sabnzbd.k3s.micasa.systems
  persistence:
    enabled: true
    volumes:
      - name: media
        existingClaimName: media
      - name: sabnzbd-config
        #existingClaimName: saabnzbd-config
        size: 250M
        accessMode: "ReadWriteOnce"
        storageClassName: "zfs"
    volumeMounts:
      - name: media
        mountPath: /media
      - name: sabnzbd-config
        mountPath: /config
