qtorrent:
  image: 
    repository: linuxserver/qbittorrent
  persistence: 
    enabled: true
    volumes:
      - name: qtorrent-config
        #existingClaimName: qtorrent-config
        size: 250M
        storageClassName: zfs
        accessMode: ReadWriteOnce
      - name: qtorrent-dl
        #existingClaimName: qtorrent-dl
        size: 50G
        storageClassName: nfs-client
        accessMode: ReadWriteMany
    volumeMounts:
      - name: qtorrent-config
        mountPath: /config
      - name: qtorrent-dl
        mountPath: /downloads
  vpn:
    enabled: true
    credentials: 
      secretName: vpn-secret
      password: "REDACTED"
      username: "REDACTED"
    env:
      - name: VPN_SERVICE_PROVIDER
        value: "nordvpn"
      - name: SERVER_COUNTRIES
        value: "United Kingdom"
    volumes:
      - name: gluetun-config
        size: 250M
        storageClassName: "zfs"
        accessMode: ReadWriteOnce
    volumeMounts: 
      - name: gluetun-config
        mountPath: /gluetun

