apiVersion: v2
name: syncthing
description: syncthing
type: application
version: 1.0.0

dependencies:
  - name: syncthing
    version: 2.1.1
    repository: oci://oci.trueforge.org/truecharts/syncthing
