app-template:
  controller:
    type: daemonset

  image:
    repository: enix/zfs-exporter
    tag: "2.3.10"
    pullPolicy: IfNotPresent

  args:
    - --deadline=8s
    - --web.listen-address=:9134
    - --collector.pool
    - --collector.dataset-filesystem
    - --collector.dataset-volume
    # - --collector.dataset-snapshot  # enable if you want snapshot metrics

  service:
    main:
      enabled: true
      type: ClusterIP
      ports:
        http:
          port: 9134
          protocol: TCP

  # Minimal annotations if your vmagent scrapes by annotations
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9134"
    prometheus.io/path: /metrics

  # Privileged + host mounts for ZFS access
  securityContext:
    privileged: true
    runAsUser: 0
    runAsNonRoot: false
    allowPrivilegeEscalation: true
  persistence:
    dev:
      enabled: true
      type: hostPath
      hostPath: /dev
      mountPath: /dev
      readOnly: false
    etc-zfs:
      enabled: true
      type: hostPath
      hostPath: /etc/zfs
      mountPath: /etc/zfs
      readOnly: true
    usr-sbin:
      enabled: true
      type: hostPath
      hostPath: /usr/sbin
      mountPath: /usr/sbin
      readOnly: true
    sbin:
      enabled: true
      type: hostPath
      hostPath: /sbin
      mountPath: /sbin
      readOnly: true

  nodeSelector:
    kubernetes.io/os: linux
  tolerations:
    - operator: Exists

  resources: {}
