zfs-exporter:
  fullnameOverride: zfs-exporter
  kind: DaemonSet

  image:
    repository: enix/zfs-exporter
    tag: "2.3.10"
    pullPolicy: IfNotPresent

  # exporter flags
  args:
    - --deadline=8s
    - --web.listen-address=:9134
    - --collector.pool
    - --collector.dataset-filesystem
    - --collector.dataset-volume
    # - --collector.dataset-snapshot  # enable if you want snapshot metrics too

  # Service for vmagent scraping
  service:
    enabled: true
    type: ClusterIP
    port: 9134
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9134"
      prometheus.io/path: /metrics

  # HARD OFF for Prometheus-Operator CRDs (so no ServiceMonitor/PodMonitor/Rules get rendered)
  serviceMonitor:
    enabled: false
  podMonitor:
    enabled: false
  prometheusRule:
    enabled: false
  monitoring:
    serviceMonitor:
      enabled: false
    podMonitor:
      enabled: false
    prometheusRule:
      enabled: false
  metrics:
    serviceMonitor:
      enabled: false
    podMonitor:
      enabled: false
    prometheusRule:
      enabled: false

  # Needs host ZFS access
  securityContext:
    privileged: true
    runAsUser: 0
    runAsNonRoot: false
    allowPrivilegeEscalation: true

  extraVolumes:
    - name: dev
      hostPath: { path: /dev }
    - name: etc-zfs
      hostPath: { path: /etc/zfs, type: DirectoryOrCreate }
    - name: usr-sbin
      hostPath: { path: /usr/sbin }
    - name: sbin
      hostPath: { path: /sbin }

  extraVolumeMounts:
    - { name: dev,      mountPath: /dev }
    - { name: etc-zfs,  mountPath: /etc/zfs,  readOnly: true }
    - { name: usr-sbin, mountPath: /usr/sbin, readOnly: true }
    - { name: sbin,     mountPath: /sbin,     readOnly: true }

  nodeSelector:
    kubernetes.io/os: linux
  tolerations:
    - operator: Exists

  resources: {}
