alertmanager:
  ingress:
    enabled: false
    className: ""
    labels: {}
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: alertmanager.k3s.micasa.systems
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - hosts:
          - alertmanager.k3s.micasa.systems
        secretName: alertmanager-tls