alertmanager:
  config:
    global:
      smtp_smarthost: "gmail-smtp-in.l.google.com:25"   # or :587 / :465 as your MTA uses
      smtp_from: "alerts@mail.micasa.systems"
      # If your server wants STARTTLS but no auth:
      # smtp_require_tls: true
      # If it's plain port 25 with no TLS on your LAN:
      smtp_require_tls: false
      # Optional but helpful (matches reverse DNS / allowlist rules):
      smtp_hello: "alertmanager.k3s.micasa.systems"

  
  route:
    receiver: "email-me"
    group_by: ["alertname","namespace"]
    group_wait: 15s
    group_interval: 5m
    repeat_interval: 12h

  receivers:
    - name: "email-me"
      email_configs:
        - to: "tezmobile@googlemail.com"
          send_resolved: true
          # If the server has a self-signed cert and you **must** skip verification (prefer CA file instead):
          # tls_config:
          #   insecure_skip_verify: true

  ingress:
    enabled: true
    className: "traefik "
    labels: {}
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: alertmanager.k3s.micasa.systems
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - hosts:
          - alertmanager.k3s.micasa.systems