alertmanager:
  config:
    global:
      smtp_smarthost: "gmail-smtp-in.l.google.com:25"   # or :587 / :465 as your MTA uses
      smtp_from: "alerts@thurcombe.com"
      # If your server wants STARTTLS but no auth:
      # smtp_require_tls: true
      # If it's plain port 25 with no TLS on your LAN:
      smtp_require_tls: false
      # Optional but helpful (matches reverse DNS / allowlist rules):
      smtp_hello: "alertmanager.k3s.micasa.lan"
    route:
      receiver: "email-me"
      group_by: ["alertname","namespace", "pool"]
      group_wait: 15s
      group_interval: 5m
      repeat_interval: 2h
    receivers:
      - name: "email-me"
        email_configs:
          - to: "tezmobile@googlemail.com"
            send_resolved: true
            html: '{{ template "email.default.html" . }}'
            headers:
              subject: '[AM] {{ .Status | toUpper }} {{ if eq (len .Alerts) 1 }}{{ (index .Alerts 0).Labels.alertname }}{{ else }}{{ len .Alerts }} alerts{{ end }}'
    templates:
      - "/etc/alertmanager/templates/*.tmpl"
  templateFiles:
    email.default.tmpl: |
      {{ define "email.default.html" }}
      <div style="font-family:system-ui,-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif">
        <h2 style="margin:0 0 8px 0">
          [{{ .Status | toUpper }}]
          {{ if eq (len .Alerts) 1 }}
            {{ (index .Alerts 0).Labels.alertname }}
          {{ else }}
            {{ len .Alerts }} alerts
          {{ end }}
        </h2>
        {{ if .GroupLabels }}
        <p style="margin:0 0 12px 0; color:#666;">
          {{- range $k, $v := .GroupLabels -}}
            <span style="display:inline-block; padding:2px 6px; border-radius:4px; background:#f1f1f1; margin-right:6px;">
              {{$k}}=<code>{{$v}}</code>
            </span>
          {{- end -}}
        </p>
        {{ end }}
        {{ if .CommonAnnotations.summary }}
        <p style="margin:0 12px 12px 0"><strong>{{ .CommonAnnotations.summary }}</strong></p>
        {{ end }}
        <table cellpadding="6" cellspacing="0" border="0" style="border-collapse:collapse; width:100%; max-width:900px">
          <thead>
            <tr style="border-bottom:1px solid #ddd">
              <th align="left">Severity</th>
              <th align="left">Alert</th>
              <th align="left">Namespace</th>
              <th align="left">Object</th>
              <th align="left">Started</th>
              <th align="left">Description</th>
            </tr>
          </thead>
          <tbody>
            {{ range .Alerts }}
            <tr style="border-top:1px solid #eee">
              <td>{{ or .Labels.severity "unknown" }}</td>
              <td>{{ .Labels.alertname }}</td>
              <td>{{ or .Labels.namespace "-" }}</td>
              <td>
                {{- if .Labels.pod -}}pod/{{ .Labels.pod }}
                {{- else if .Labels.deployment -}}deploy/{{ .Labels.deployment }}
                {{- else if .Labels.instance -}}{{ .Labels.instance }}
                {{- else -}}-{{- end -}}
              </td>
              <td>{{ .StartsAt }}</td>
              <td>
                {{- if .Annotations.summary -}}{{ .Annotations.summary }}{{- end -}}
                {{- if and .Annotations.summary .Annotations.description -}} — {{- end -}}
                {{- if .Annotations.description -}}{{ .Annotations.description }}{{- end -}}
              </td>
            </tr>
            {{ end }}
          </tbody>
        </table>
        {{ if .ExternalURL }}
        <p style="margin-top:12px">
          <a href="{{ .ExternalURL }}" style="text-decoration:none">Open Alertmanager</a>
        </p>
        {{ end }}
      </div>
      {{ end }}
  extraArgs:
    log.level: debug
  ingress:
    enabled: true
    className: "traefik "
    labels: {}
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: alertmanager.k3s.micasa.systems
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - hosts:
          - alertmanager.k3s.micasa.systems