pihole:
  virtualHost: pihole.k3s.micasa.systems
  persistentVolumeClaim:
    enabled: true
    storageClass: zfs
    size: 500M
  dnsHostPort:
    enabled: false
  serviceDns:
    type: LoadBalancer
  