apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-micasa-systems
  namespace: traefik
spec:
  dnsNames:
  - "traefik.{{ .valuesClusterDNSName }}"
  secretName: traefik-micasa-systems
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
