apiVersion: v1
kind: Service
metadata:
  annotations: {}
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-23.1.0
  name: traefik-dnstcp
  namespace: traefik
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
  selector:
    app.kubernetes.io/instance: traefik-traefik
    app.kubernetes.io/name: traefik
  sessionAffinity: None
  type: LoadBalancer
