apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard
  namespace: traefik
spec:
  secretName: star-dot-certificate
  dnsNames:
  - "*.{{ .Values.clusterDNSName }}"
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
