external-dns:
  env:
  - name: EXTERNAL_DNS_PIHOLE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: pihole-admin
        key: password
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-token
        key: api-token
  registry: noop
  provider:
   name: cloudflare
  sources:
  - ingress
  extraArgs:
  - --pihole-server=http://pihole-web.pihole.svc.cluster.local