env:
- name: EXTERNAL_DNS_PIHOLE_PASSWORD
  valueFrom:
    secretKeyRef:
      name: pihole-admin
      key: password
registry: noop
provider: 
  name: pihole
sources:
#- service
- ingress
extraArgs:
- --pihole-server=http://pihole-web.pihole.svc.cluster.local  