# --- kube-state-metrics ---
kube-state-metrics: {}

# --- VictoriaMetrics Single ---
victoria-metrics-single:
  # keep it small; tune to taste
  server:
    retentionPeriod: 15d
    persistentVolume:
      enabled: true
      size: 1Gi
      storageClassName: zfs
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        memory: 512Mi

  # Use VM Single to scrape kube-state-metrics directly (lighter than adding vmagent)
  scrape:
    config: |
      global:
        scrape_interval: 30s
      scrape_configs:
        - job_name: "kube-state-metrics"
          static_configs:
            # Service name produced by this umbrella + subchart: <release>-kube-state-metrics
            - targets: ["k8s-pod-alerts-lite-kube-state-metrics.monitoring.svc:8080"]

# --- vmalert (VictoriaMetrics Alert) ---
victoria-metrics-alert:
  # Point vmalert at VM Single as its datasource and your existing Alertmanager as notifier.
  vmalert:
    spec:
      datasource:
        # vmsingle exposes query API on 8428
        url: "http://k8s-pod-alerts-lite-victoria-metrics-single.monitoring.svc:8428"
      notifier:
        url: "http://alertmanager.alertmanager.svc:9093"
      # We only need alerting; disable remote write for recording rules
      evaluationInterval: "30s"

  # Inline the alerting rules you asked for (CrashLoopBackOff, ImagePullBackOff, Pending, NotReady)
  rules:
    groups:
      - name: "kubernetes.pods.light"
        interval: "30s"
        rules:
          - alert: KubePodCrashLooping
            expr: max_over_time(kube_pod_container_status_waiting_reason{reason="CrashLoopBackOff"}[5m]) >= 1
            for: 2m
            labels: { severity: critical }
            annotations:
              summary: "Pod crash looping ({{ $labels.namespace }}/{{ $labels.pod }})"
              description: "Container {{ $labels.container }} is in CrashLoopBackOff."

          - alert: KubePodImagePullBackOff
            expr: max_over_time(kube_pod_container_status_waiting_reason{reason=~"ImagePullBackOff|ErrImagePull"}[5m]) >= 1
            for: 5m
            labels: { severity: warning }
            annotations:
              summary: "Image pull issue ({{ $labels.namespace }}/{{ $labels.pod }})"
              description: "Container {{ $labels.container }} has image pull errors."

          - alert: KubePodPendingTooLong
            expr: sum by (namespace,pod) (kube_pod_status_phase{phase="Pending"}) > 0
            for: 10m
            labels: { severity: warning }
            annotations:
              summary: "Pod pending >10m ({{ $labels.namespace }}/{{ $labels.pod }})"
              description: "Pod has been Pending for over 10 minutes."

          - alert: KubePodNotReady
            expr: sum by (namespace,pod) (kube_pod_status_ready{condition="true"}) < 1
            for: 5m
            labels: { severity: critical }
            annotations:
              summary: "Pod not ready ({{ $labels.namespace }}/{{ $labels.pod }})"
              description: "Pod has no Ready containers for 5 minutes."
