# --- kube-state-metrics ---
kube-state-metrics: {}

# --- VictoriaMetrics Single ---
victoria-metrics-single:
  server:
    retentionPeriod: 15d
    persistentVolume:
      enabled: true
      size: 1Gi
      storageClassName: local-path
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        memory: 512Mi

    # ✅ enable inline scrape config and point it at kube-state-metrics
    scrape:
      enabled: true
      config: |
        global:
          scrape_interval: 30s
        scrape_configs:
          - job_name: "kube-state-metrics"
            static_configs:
              - targets: ["victoria-alerts-kube-state-metrics.monitoring.svc:8080"]

# --- vmalert (VictoriaMetrics Alert) ---
victoria-metrics-alert:
  server:
    # ✅ REQUIRED: where vmalert reads metrics (Prometheus-compatible API)
    datasource:
      url: "http://victoria-alerts-victoria-metrics-single.monitoring.svc:8428"

    # ✅ where vmalert sends alerts (your existing Alertmanager)
    notifier:
      alertmanager:
        url: "http://alertmanager.alertmanager.svc:9093"

    # ✅ the actual alert rules you wanted
    config:
      alerts:
        groups:
          - name: "kubernetes.pods.light"
            interval: "30s"
            rules:
              - alert: KubePodCrashLooping
                expr: max_over_time(kube_pod_container_status_waiting_reason{reason="CrashLoopBackOff"}[5m]) >= 1
                for: 2m
                labels: { severity: critical }
                annotations:
                  summary: "Pod crash looping ({{ $labels.namespace }}/{{ $labels.pod }})"
                  description: "Container {{ $labels.container }} is in CrashLoopBackOff."

              - alert: KubePodImagePullBackOff
                expr: max_over_time(kube_pod_container_status_waiting_reason{reason=~"ImagePullBackOff|ErrImagePull"}[5m]) >= 1
                for: 5m
                labels: { severity: warning }
                annotations:
                  summary: "Image pull issue ({{ $labels.namespace }}/{{ $labels.pod }})"
                  description: "Container {{ $labels.container }} has image pull errors."

              - alert: KubePodPendingTooLong
                expr: sum by (namespace,pod) (kube_pod_status_phase{phase="Pending"}) > 0
                for: 10m
                labels: { severity: warning }
                annotations:
                  summary: "Pod pending >10m ({{ $labels.namespace }}/{{ $labels.pod }})"
                  description: "Pod has been Pending for over 10 minutes."

              - alert: KubePodNotReady
                expr: sum by (namespace,pod) (kube_pod_status_ready{condition="true"}) < 1
                for: 5m
                labels: { severity: critical }
                annotations:
                  summary: "Pod not ready ({{ $labels.namespace }}/{{ $labels.pod }})"
                  description: "Pod has no Ready containers for 5 minutes."
