jackett:
    persistence:
        enabled: true
        volumes:
            - name: "jackett-config"
              storageClassName: "zfs"
              size: 250M
              accessMode: "ReadWriteOnce"
        volumeMounts:
          - name: jackett-config
            mountPath: /config
    ingress:
        enabled: true
        hostName: jackett.k3s.micasa.systems
        className: traefik
        tls:
            enabled: true

