qbittorrent:
  env:
    - name: PUID
      value: "65533"
    - name: PGID
      value: "65533"
  image: 
    repository: linuxserver/qbittorrent
  ingress:
    enabled: true
    className: traefik
    hosts:
        - host: qbittorrent.k3s.micasa.systems
          paths:
            - path: /
              pathType: ImplementationSpecific
    tls:
        - hosts:
            - qbittorrent.k3s.micasa.systems

  persistence: 
    enabled: true
    volumes:
      - name: qbittorrent-config
        #existingClaimName: qtorrent-config
        size: 250M
        storageClassName: zfs
        accessMode: ReadWriteOnce
      - name: media
        size: 200G
        storageClassName: local-path
        accessMode: ReadWriteOnce
    volumeMounts:
      - name: qbittorrent-config
        mountPath: /config
      - name: media
        mountPath: /media
  vpn:
    enabled: true
    provider:
      name: protonvpn
      protocol: wireguard
      credentials:
        wireguard:
          privateKey: "REDACTED"
      configuration:
        dns_address: "1.1.1.1"
    env:
      - name: DNS_ADDRESS
        value: "1.1.1.1"
      - name: VPN_SERVICE_PROVIDER
        value: "nordvpn"
      - name: SERVER_COUNTRIES
        value: "United Kingdom"
    volumes:
      - name: gluetun-config
        size: 250M
        storageClassName: "zfs"
        accessMode: ReadWriteOnce
    volumeMounts: 
      - name: gluetun-config
        mountPath: /gluetun

