apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pihole
  namespace: pihole
spec:
  dnsNames:
    - {{ .Values.pihole.virtualHost }}
  secretName: pihole-certificate
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
