apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pihole
  namespace: pihole
spec:
  dnsNames:
    - "{{ .Values.dnsName }}"
  secretName: pihole-certificate
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
