apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pihole-web-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
        - {{ .Values.pihole.virtualHost }}
      secretName: pihole-web-certificate
  rules:
    - host: {{ .Values.pihole.virtualHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pihole-web
                port:
                  number: 80
