apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: ingressroute-dns-udp
  namespace: pihole
spec:
  entryPoints:
    - dns-udp
  routes:
    - services:
        - name: pihole-dns-udp
          port: 8753
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: ingressroute-dns-tcp
  namespace: pihole
spec:
  entryPoints:
    - dns-tcp
  routes:
    - match: HostSNI(`*`)
      services:
        - name: pihole-dns-tcp
          port: 8853
