apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}
  certificate:
    subject:
      organization: 
        - "Micasa Systems"
      organizationalUnit:
      - "Home"
      country:
      - "UK"

