headlamp:
  config:
    inCluster: true
  ingress:
    enabled: true
    ingressClassName: traefik

    hosts:
     - host: ui.k3s.micasa.systems
       paths:
         - path: /
           type: ImplementationSpecific
    tls:
      - hosts:
        - ui.k3s.micasa.systems
  persistentVolumeClaim:
    enabled: true
    storageClassName: zfs
    size: 10Gi
    accessModes:
      - ReadWriteOnce
