apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: syncthing
  namespace: argocd
spec:
  project: default
  destination:
    name: in-cluster
    namespace: apps
  source:
    repoURL: oci://oci.trueforge.org/truecharts/syncthing
    targetRevision: 10.0.14
    path: .                          
    helm:
      values: |
        persistence:
          media:
            enabled: true
            type: pvc
            existingClaim: media
            mountPath: /media
            subPath: "downloads/syncthing"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true