argo-cd:
  crds:
    # -- Install and upgrade CRDs
    install: true
    # -- Keep CRDs on chart uninstall
    keep: true

  global:
    domain: argo.k3s.micasa.systems

  ingress:
    enabled: true
    ingressClassName: traefik
    tls: true
    annotations:
      cert-manager.io/cluster-issuer: selfsigned
