argo-cd:
  config:
    repositories:
      - url: "https://gitlab.com/n3wz/deployment.git"
        token: ""
        ssh: false
    git:
      token: ""
  dex:
    enabled: false
  crds:
    # -- Install and upgrade CRDs
    install: true
    # -- Keep CRDs on chart uninstall
    keep: true

  global:
    domain: argo.k3s.micasa.systems

  server:
    ingress:
      enabled: true
      ingressClassName: traefik
      tls: true
      annotations:
        cert-manager.io/cluster-issuer: selfsigned
