prowlarr:
  livenessProbe: {}
#    httpGet:
#      path: /
#      port: http
  readinessProbe: {}
#    httpGet:
#      path: /
#      port: http
  service:
    type: ClusterIP
    port: 9696
  persistence:
      enabled: true
      volumes:
        - name: prowlarr-config
          storageClassName: "zfs"
          size: 1G
          accessMode: "ReadWriteOnce"
      volumeMounts:
        - name: prowlarr-config
          mountPath: /config
  ingress:
      enabled: true
      ingressClassName: traefik
      tls:
          - hosts:
              - "prowlarr.k3s.micasa.systems"
      hosts:
       - host: "prowlarr.k3s.micasa.systems"
         paths: 
          - path: /
            pathType: ImplementationSpecific

