mailu:
  global:
    storageClass: zfs
  hostnames:
  - micasa.systems
  - k3s.micasa.systems
  - mail.micasa.systems
  domain: micasa.systems
  fetchmail:
    enabled: true
    logLevel: debug
  initialAccount:
    enabled: true
    domain: micasa.systems
    username: mailadmin
  ingress:
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
