mailu:
  global:
    storageClass: zfs
  hostnames:
  - mail.k3s.micasa.systems
  domain: micasa.systems
    - mail.mydomain.com
  initialAccount:
    domain: micasa.systems
    username: mailadmin
  ingress:
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt