mailu:
  global:
    storageClass: zfs
  hostnames:
  - mail.k3s.micasa.systems
  domain: micasa.systems
  ingress:
    ingressClassName: traefik
    annotations:
    - cert-manager.io/cluster-issuer: letsencrypt