mailu:
  global:
    storageClass: zfs
  hostnames:
  - micasa.systems
  - k3s.micasa.systems
  - mail.micasa.systems
  domain: micasa.systems
  persistence:
    storageClass: zfs
    single_pvc: false
  dovecot:
    persistence:
        storageClass: zfs
  postfix:
    persistence:
        storageClass: zfs
  admin:
    persistence:
      storageClass: zfs
  rspamd:
    persistence:
      storageClass: zfs
  fetchmail:
    enabled: true
    logLevel: debug
    persistence:
        storageClass: zfs
  initialAccount:
    enabled: true
    domain: micasa.systems
    username: mailadmin
  ingress:
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
